{
 "title": "cplace HTTP Access",
 "description": "cplace HTTP Access Dashboard",
 "tags": [
  "cplace",
  "http",
  "access",
  "logs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{\"find\":\"terms\", \"field\":\"kubernetes.namespace_name.keyword\",\"query\":\"requested_uri!=null\"}"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "{\n\"find\":\"terms\",\"field\":\"kubernetes.labels.app_kubernetes_io/instance.keyword\",\n\"query\":\"level_value!=null AND kubernetes.namespace_name=$namespace\"\n}"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "{\"find\":\"terms\",\"field\":\"kubernetes.pod_name.keyword\",\"query\":\"requested_uri!=null AND kubernetes.namespace_name.keyword:$namespace AND kubernetes.labels.app_kubernetes_io\\\\/instance.keyword:$instance\"}"
   },
   {
    "name": "inter",
    "label": "Interval",
    "query": "1s,5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total requests",
   "type": "graph",
   "description": "Total requests in given Interval",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "status_code",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "status_code",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.namespace_name:\"$namespace\" AND kubernetes.labels.app_kubernetes_io\\/instance:\"${instance}\" AND _exists_:status_code",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.pod_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "status_code",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.namespace_name:\"$namespace\" AND kubernetes.labels.app_kubernetes_io\\/instance:\"${instance}\" AND status_code!=null",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Unique Visits (external)",
   "type": "graph",
   "description": "Unique visits without internal (monitoring) requests",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "remote_host.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "kubernetes.namespace_name:\"$namespace\" AND kubernetes.labels.app_kubernetes_io\\/instance:\"${instance}\" AND status_code!=null AND NOT remote_host.keyword: /(192\\.168).*/",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "User Agents Top 10",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "request_headers.user-agent.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.namespace_name:\"$namespace\" AND kubernetes.labels.app_kubernetes_io\\/instance:\"${instance}\" AND status_code!=null AND request_headers.user-agent!=null",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Request Timing",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "method.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "time", "id": "2", "settings": { "interval": "$inter", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "elapsed_time",
       "id": "1",
       "meta": {
        "avg": false,
        "count": false,
        "max": false,
        "min": false,
        "std_deviation": true,
        "std_deviation_bounds_lower": true,
        "std_deviation_bounds_upper": true,
        "sum": false
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "kubernetes.namespace_name:\"$namespace\" AND kubernetes.labels.app_kubernetes_io\\/instance:\"$instance\" AND _exists_:status_code AND _exists_:elapsed_time",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "Recent Request (external)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs",
     "type": "table",
     "description": "Show 500 recent requests  (excluding internal networks)",
     "gridPos": { "h": 27, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 500 },
         "type": "raw_document"
        }
       ],
       "query": "kubernetes.namespace_name:\"$namespace\" AND kubernetes.labels.app_kubernetes_io\\/instance:\"${instance}\" AND _exists_:status_code AND NOT remote_host.keyword: /(192\\.168).*/",
       "timeField": "time"
      }
     ]
    }
   ]
  }
 ]
}