{
 "title": "cplace Application Logs",
 "description": "cplace Application Logs",
 "tags": [ "logs" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "{\"find\":\"terms\", \"field\":\"kubernetes.namespace_name.keyword\"}"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "{\"find\":\"terms\",\"field\":\"kubernetes.labels.app_kubernetes_io/instance.keyword\",\"query\":\"kubernetes.namespace_name.keyword:$namespace\"}"
   },
   {
    "name": "level",
    "label": "Log Level",
    "query": "{\"find\":\"terms\",\"field\":\"level.keyword\",\"size\": 10,\"query\":\"kubernetes.labels.app_kubernetes_io\\\\/instance.keyword:$instance\"}"
   },
   {
    "name": "logger",
    "label": "Logger Name",
    "query": "{\"find\": \"terms\", \"field\": \"logger_name.keyword\", \"size\": 200, \"query\":\"kubernetes.labels.app_kubernetes_io\\\\/instance.keyword:$instance AND level.keyword:$level\"}"
   },
   { "name": "filter", "label": "Search", "query": "*" }
  ]
 },
 "panels": [
  {
   "title": "Logs per Instance",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.labels.app_kubernetes_io/instance.keyword",
       "id": "3",
       "settings": { "min_doc_count": 10, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      { "field": "es_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.namespace_name.keyword:$namespace",
     "timeField": "es_time"
    }
   ]
  },
  {
   "type": "graph",
   "description": "Chart for incoming logs by level",
   "gridPos": { "h": 6, "w": 20, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Info",
     "bucketAggs": [
      { "field": "es_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "status_code",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "count"
      }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/instance:$instance AND level:$level AND logger_name:$logger AND ${filter:glob} AND level:INFO",
     "timeField": "es_time"
    },
    {
     "alias": "Warn",
     "bucketAggs": [
      { "field": "es_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/instance:$instance AND level:$level AND logger_name:$logger AND ${filter:glob} AND level:WARN",
     "timeField": "es_time"
    },
    {
     "alias": "Error",
     "bucketAggs": [
      { "field": "es_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/instance:$instance AND level:$level AND logger_name:$logger AND ${filter:glob} AND level:ERROR",
     "timeField": "es_time"
    },
    {
     "alias": "Debug",
     "bucketAggs": [
      { "field": "es_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/instance:$instance AND level:$level AND logger_name:$logger AND ${filter:glob} AND level:DEBUG",
     "timeField": "es_time"
    }
   ]
  },
  {
   "title": "All Logs for selected instance",
   "type": "logs",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "es_time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/instance:$instance",
     "timeField": "es_time"
    }
   ]
  },
  {
   "title": "Log Table",
   "type": "table",
   "gridPos": { "h": 26, "w": 23, "x": 0, "y": 18 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "kubernetes.labels.app_kubernetes_io\\/instance:$instance AND level:$level AND logger_name:$logger AND ${filter:glob}",
     "timeField": "es_time"
    }
   ]
  }
 ]
}