{
 "title": "Fluent-bit Metrics",
 "tags": [
  "fluent-bit",
  "metrics"
 ],
 "time": { "from": "now-60m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=\"logging\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Fluent Bit Bytes ingested",
   "type": "graph",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(fluentbit_input_bytes_total[5m]))",
     "legendFormat": "Input Bytes"
    },
    {
     "expr": "avg(rate(fluentbit_input_records_total[5m]))",
     "legendFormat": "Input Records"
    }
   ]
  },
  {
   "title": "Fluent Bit Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(fluentbit_output_errors_total[5m]))",
     "legendFormat": "Output Errors"
    },
    {
     "expr": "avg(rate(fluentbit_output_retries_total[5m]))",
     "legendFormat": "Output Retries"
    },
    {
     "expr": "avg(rate(fluentbit_output_retries_failed_total[5m]))",
     "legendFormat": "Output Retries Failed"
    }
   ]
  },
  {
   "title": "Records Overview",
   "type": "graph",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(fluentbit_filter_drop_records_total[5m]))",
     "legendFormat": "Filter Drop Records"
    },
    {
     "expr": "avg(rate(fluentbit_filter_add_records_total[5m]))",
     "legendFormat": "Filter Add Records"
    }
   ]
  },
  {
   "title": "Fluent-Bit logs",
   "type": "table",
   "gridPos": { "h": 26, "w": 22, "x": 0, "y": 29 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "kubernetes.container_name=\"fluent-bit\"",
     "timeField": "time"
    }
   ]
  }
 ]
}